version: "3"
services:
  database:
    image: postgres
    container_name: transitions-db
    restart: unless-stopped
    # Load all env vars from .env into the container's environment.
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./api/src/db/migration.sql:/docker-entrypoint-initdb.d/migration.sql
      - ./api/src/db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
  server:
    image: hacking-transitions-20/api
    container_name: transitions-api
    restart: unless-stopped
    build: ./api
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database/${POSTGRES_DB}
      NODE_ENV: development
      PORT: 80
    depends_on:
      - database
    ports:
      - ${API_PORT}:80
    volumes:
      # This allows live reload inside a docker container by mapping your
      # filesystem to the container's.
      - ./api/src:/code/src
    command: npm run dev
  client:
    image: hacking-transitions-20/client
    container_name: client
    restart: unless-stopped
    build: ./client
    environment:
      API_URL: http://transitions-api
      PORT: ${CLIENT_PORT}
    depends_on:
      - server
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      # This allows live reload inside a docker container by mapping your
      # filesystem to the container's.
      - ./client/src:/code/src
    command: npm run dev
volumes:
  pg-data:
